### ISSUE TITLE
Give an example of using .env variables

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/website#328]
https://parceljs.org/env.html could benefit from an example of how a developer might use `.env` variables. One example I'm thinking of is loading different debug vs. production versions of a library. If this makes sense, how would it be implemented?

**Comment by rxliuli** [comment]
Yes, the current document is too simple, I want to achieve the following requirements

1. According to an option on the command line, load different configuration files
2. In the web environment, can the variables in the corresponding .env. * File be accessed through process.env. *
3. Does .env. * Include .env content by default

But I don't know how to use parcel, because the documentation is too simple. . .

I suggest that you can refer to vue-cli's documentation on environment variables:...
