### ISSUE TITLE
Language Selector Alignment  & Styling

### ISSUE THREAD

**Issue by brandon93s** [parcel-bundler/website#41]
**Location:**
https://en.parceljs.org/
https://ko.parceljs.org/

**Alignment:**

![image](https://user-images.githubusercontent.com/4730164/34024865-8fcc4bd2-e11a-11e7-88e1-9b5bfb2cd8a8.png)

**Hover Styling:**

![image](https://user-images.githubusercontent.com/4730164/34024863-8a51545e-e11a-11e7-8972-d18f43edc752.png)

**Comment by devongovett** [comment]
Oh hmm, there are supposed to be emoji flags there... What platform/browser are you on?

<img width="67" alt="screen shot 2017-12-15 at 8 34 46 am" src="https://user-images.githubusercontent.com/19409/34024906-d3de8f26-e172-11e7-8093-9d9fd877b871.png">

**Comment by brandon93s** [comment]
**Browser:** Chrome 63.0.3239.108 
**OS:** Windows 10

Happening in Edge as well, though.

**Comment by brandon93s** [comment]
Liking the flags, though!

**Comment by Seojiwoong** [comment]
http://www.unicode.org/emoji/charts/full-emoji-list.html

emoji does not support national flag in desktop browser

**Comment by iStefo** [comment]
I came to the repository to drop this link: http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

The gist: Flags do not represent languages, they represent countries. One language is spoken in multiple countries and a single country can have multiple officially spoken languages.

Instead of looking into the Emoji issue, how about representing the language by its ISO 639-1 code? https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by brandon93s** [comment]
Improved by #56 and can now be used on Windows desktop. Would love to see the flags / emojis ported to svg / png still!
